### ISSUE TITLE
Make templates look pretty!

### ISSUE THREAD

**Issue by snickercop** [snickercop/WebTest#10]
The template pages for the index, upload page, etc. need to be styled with CSS and possibly reformatted with HTML. Adding bootstrap would be a quick and dirty way to do this, but do whatever suits you, as long as it's legible and easy to use.

**Comment by ritwiksingh21** [comment]
Hi. If by "need to be prettified"  you meant to have css work done, then please tell me. I would be really happy to contribute.

**Comment by snickercop** [comment]
Yes, that's what I mean! Go for it!

**Comment by ritwiksingh21** [comment]
Thanks! I am starting with the output2.html. Once its look is finalized, I'll make the style available for all pages.
