### ISSUE TITLE
Create base HTML template

### ISSUE THREAD

**Issue by snickercop** [snickercop/WebTest#15]
Make base.html (located in /questions/templates) look pretty! If you don't know where to start, you can use bootstrap--all you have to do is copy and paste; it takes about 10 minutes. [https://getbootstrap.com/](https://getbootstrap.com/)

**Comment by sunguru98** [comment]
May I take this ticket please @snickercop?

**Comment by snickercop** [comment]
Sure! Good luck :) and feel free to reach out to me if you need help, this project is realllly poorly documented atm

**Comment by sunguru98** [comment]
Great lemme, do some crap work here and cry for help later LOL

**Comment by sunguru98** [comment]
@snickercop There exists no folder called questions in the codebase. Should I create it and then place index.html, or what?

**Comment by snickercop** [comment]
Nah, it's there. wtdjango/questions.
https://github.com/snickercop/WebTest/tree/master/wtdjango/questions/templates

You'll also need to read a little bit on django templating
https://docs.djangoproject.com/en/3.0/topics/templates/. Basically, if you
see something inside {} in the existing html pages, don't mess with it.

Good luck!

**Comment by sunguru98** [comment]
Alright. Thanks for the quick response @snickercop.

**Comment by sunguru98** [comment]
Done :)
